default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: admin_billplz_development


test:
  <<: *default
  database: admin_billplz_test


production:
  <<: *default
  database: admin_billplz_production
  username: admin_billplz
  password: <%= ENV['ADMIN_BILLPLZ_DATABASE_PASSWORD'] %>
